# Generated by Django 4.2.9 on 2024-01-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_fileupload_customuser_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
